name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{github.actor }} has triggered the pipeline

on: 
 push:
   branches:
       - 'main'
env:
  AWS_ACCCESS_KEY:${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY:${{ secrets.AWS_SECRET_ACESS_KEY }}

jobs:
  build-infra:
    name:terraform-ci-cd
    runs-on:ubuntu-latest
    steps:
      -name:checkout
       uses:actions/checkout@v2
      -name:Set up terraform
       uses:hashicorp/setup-terraform@v2
      -name:Terrafrom init
       id:init
       run:terrafrom init
       working-directory: ./Terrafrom-VPC
      -name:Terrafrom validate
       id:validate
       run:terrafrom validate
       working-directory: ./Terrafrom-VPC
      -name:Terrafrom plan
       id:plan
       run:terrafrom plan
       working-directory: ./Terrafrom-VPC
      -name:Terrafrom apply
       id:apply
       run:terrafrom apply --auto-approve
       working-directory: ./Terrafrom-VPC
      


       
       
